apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "azure-api-management/gateway"
spec:
  rules:
  - http:
      paths: 
      - path: /echo
        pathType: Prefix
        backend:
          serviceName: echo-service
          servicePort: 8080 